### ISSUE TITLE
Requests to "Play" media via the SPA fail on Firefox nightly Android

### ISSUE THREAD

**Issue by Vrend** [warren-bank/crx-webcast-reloaded#9]
After installing the extension on Firefox Nightly Android v130.0a1, I was able to use the extension to find streams on a page I tested, and was able to open the SPA.

But after filling in my IP information and port, hitting play did nothing. What's strange is, if I copy and paste the link into my regular Firefox Android, it'll play as normal.

For reference, this firefox nightly android was a fresh install, with the only changes/additions being the installation of ublock origin, this extension, and the config change to allow unsigned XPI installations. 

I attempted to debug via my desktop firefox browser, but I didn't see any errors or warnings in the console when loading the page or hitting play.

**Comment by warren-bank** [comment]
quick test:

* [page](https://file-examples.com/index.php/sample-video-files/sample-mp4-files/) with sample videos
* [SPA](http://webcast-reloaded.surge.sh/airplay_sender.html#/watch/aHR0cHM6Ly9maWxlLWV4YW1wbGVzLmNvbS9zdG9yYWdlL2ZlNDRlZWI5Y2I2NmFiOGNlOTM0ZjE0LzIwMTcvMDQvZmlsZV9leGFtcGxlX01QNF80ODBfMV81TUcubXA0/referer/aHR0cHM6Ly9maWxlLWV4YW1wbGVzLmNvbS9pbmRleC5waHAvc2FtcGxlLXZpZGVvLWZpbGVzL3NhbXBsZS1tcDQtZmlsZXMv) with URL for the 1.5 MB (480x270) sample video

results:
* [Fenix Nightly: 12/11/2023](https://www.apkmirror.com/apk/mozilla/firefox-fenix/firefox-fenix-122-0a1-release/firefox-nightly-for-developers-122-0a1-88-android-apk-download/) on Android 8
  - tab in normal window
    * success
  - tab in private window
    * fail
      - URL for SPA is automatically redirected from HTTP to HTTPS, despite:
        * `Settings > HTTPS-Only Mode` = false
        * which I'll quickly note is UI to set the value for: `dom.security.https_only_mode`
    * fix
      1. open: `about:config`
      2. find: `dom.security.https_first_pbm`
      3. change value to: `false`
    * references
      - [blog](https://blog.mozilla.org/security/2021/08/10/firefox-91-introduces-https-by-default-in-private-browsing/): Firefox 91 introduces _HTTPS by Default_ in Private Browsing
      - [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1706552): introduction of `dom.security.https_first_pbm` preference

**Comment by warren-bank** [comment]
note:
* a less secure alternative is to allow insecure (HTTP) mixed content XHR requests from secure (HTTPS) pages
  1. open: `about:config`
  2. find: `security.mixed_content.block_active_content`
  3. change value to: `false`
* this would allow the SPA to load from HTTPS, and communicate with _ExoAirPlayer_ over HTTP
  - but it opens an unnecessary security vulnerability
  - better to just load the SPA from HTTP, and not have to worry about mixed content

**Comment by Vrend** [comment]
> quick test:
> 
>     * [page](https://file-examples.com/index.php/sample-video-files/sample-mp4-files/) with sample videos
> 
>     * [SPA](http://webcast-reloaded.surge.sh/airplay_sender.html#/watch/aHR0cHM6Ly9maWxlLWV4YW1wbGVzLmNvbS9zdG9yYWdlL2ZlNDRlZWI5Y2I2NmFiOGNlOTM0ZjE0LzIwMTcvMDQvZmlsZV9leGFtcGxlX01QNF80ODBfMV81TUcubXA0/referer/aHR0cHM6Ly9maWxlLWV4YW1wbGVzLmNvbS9pbmRleC5waHAvc2FtcGxlLXZpZGVvLWZpbGVzL3NhbXBsZS1tcDQtZmlsZXMv) with URL for the 1.5 MB (480x270) sample video
> 
> 
> results:
> 
>     * [Fenix Nightly: 12/11/2023](https://www.apkmirror.com/apk/mozilla/firefox-fenix/firefox-fenix-122-0a1-release/firefox-nightly-for-developers-122-0a1-88-android-apk-download/) on Android 8
>       
>       * tab in normal window
>         
>         * success
>       * tab in private window
>         
>         * fail
>           
>           * URL for SPA is automatically redirected from HTTP to HTTPS, despite:
>             
>             * `Settings > HTTPS-Only Mode` = false
>             * which I'll quickly note is UI to set the value for: `dom.security.https_only_mode`
>         * fix
>           
>           1. open: `about:config`
>           2. find: `dom.security.https_first_pbm`
>           3. change value to: `false`
>         * references
>           
>           * [blog](https://blog.mozilla.org/security/2021/08/10/firefox-91-introduces-https-by-default-in-private-browsing/): Firefox 91 introduces _HTTPS by Default_ in Private Browsing
>           * [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1706552): introduction of `dom.security.https_first_pbm` preference

I had to set dom.security.https_first to false in order to get videos playing, on Android 12.

On an older version of android (FireOS 7), I was able to install (after changing to a zip) and it worked without modification.

**Comment by warren-bank** [comment]
For clarity.. for anybody else who may stumble across this issue:

[This post](https://groups.google.com/a/mozilla.org/g/dev-platform/c/yt6Kc8cAHag), which is dated 6/6/2024, is essentially a PSA to announce the change in Firefox Nightly that the default value for the preference `dom.security.https_first` is being changed from `false` to `true`.

Since I was testing with a FF Nightly from 12/11/2023 (ie: the last one that supports installing addons from a local file when running on Android < 10), the default value for the preference `dom.security.https_first` was `false`.. which is why my test in a normal window was successful.

Since you were testing with a FF Nightly from 8/1/2024, the default value for the preference `dom.security.https_first` was `true`.. which is why you needed to change its value to `false` for the SPA to load properly in a normal window.

**Comment by warren-bank** [comment]
notes (to self) regarding deployment of website to `surge.sh`:

* previously, I had run:
  ```bash
    surge --domain "webcast-reloaded.surge.sh"
  ```
  - doing so enabled access through both `http` and `https`, without any automatic redirect from one to the other
* [this issue](https://github.com/sintaxi/surge/issues/398) explains that it is possible to only enable a single protocol, which will automatically redirect from the other
  - relevant code: [1](https://github.com/sintaxi/surge/blob/v0.23.1/lib/middleware/protocol.js#L9), [2](https://github.com/sintaxi/surge/blob/v0.23.1/lib/middleware/deploy.js#L60)
  - note: the `--force http` option appears to no-longer be implemented in code
* now, I have run:
  ```bash
    surge --domain "http://webcast-reloaded.surge.sh"
  ```
  - to only enable access with `http` protocol
  - test:
    * request:
      ```bash
        curl -I "https://webcast-reloaded.surge.sh/airplay_sender.html"
      ```
    * response:
      ```bash
        HTTP/1.1 301 Moved Permanently
        Location: http://webcast-reloaded.surge.sh/airplay_sender.html
      ```
  - relevance:
    * the `HTTPS-First` policy in Firefox/Fenix, and the preferences that configure its behavior, will no-longer have any effect
    * Firefox/Fenix will fail when it attemps to automatically upgrade protocol from `http` to `https`
